
// * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
// * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
// */
//package vista;

import controlador.MarcaControlador;
import controlador.ProductoControlador;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import modelo.Marca;

/**
 *
 * @author KEVIN
 */
public class VistaMarca extends javax.swing.JFrame {
//ArrayList<String[]> lM;
//ArrayList<String[]> lP;
//    /**
//     * Creates new form VistaMarca
//     */
//    public VistaMarca() {
//        initComponents();
//        seleccionarMarca();
//        listaProducto();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProducto = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        cmbProductos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtADetalle = new javax.swing.JTextArea();
        cmbMarcas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblProducto.setText("PRODUCTO");

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAgregar.setText("+");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnPDF.setText("GENERAR PDF");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblTitulo.setText("GESTIÓN DE FACTURAS");

        cmbProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbProductosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbProductosMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmbProductosMousePressed(evt);
            }
        });
        cmbProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductosActionPerformed(evt);
            }
        });

        txtADetalle.setEditable(false);
        txtADetalle.setColumns(20);
        txtADetalle.setRows(5);
        jScrollPane1.setViewportView(txtADetalle);

        cmbMarcas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMarcasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(241, 241, 241))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPDF)
                        .addGap(252, 252, 252))))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(cmbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnAgregar)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(lblProducto)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPDF)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
//        Producto p = new Producto();
//        p.setId(Integer.parseInt(lP.get(this.productoSeleccionado())[0]));
//        p.setNombre(lP.get(this.productoSeleccionado())[1]);
//        p.setPrecio(Double.parseDouble(lP.get(this.productoSeleccionado())[2]));
//        //OBJETO DETALLE FACTURA
//        DetalleFactura dF = new DetalleFactura();
//        dF.setProducto(p);
//        dF.setCantidad(Integer.parseInt(txtCantidad.getText()));
//        dF.setSubtotal(Double.parseDouble(txtSubTotal.getText()));
//        //Añado a la lista dinámica
//        lDF.add(dF);
//        //muestro en la vista en el TextArea
//        txtADetalle.append(dF.toString());
//        this.limpiarDetalle();

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cmbProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbProductosMouseClicked

    }//GEN-LAST:event_cmbProductosMouseClicked

    private void cmbProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbProductosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProductosMouseEntered

    private void cmbProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbProductosMousePressed
        // TODO add your handling code here:
//        Object o = cmbProductos.getSelectedItem();
    }//GEN-LAST:event_cmbProductosMousePressed

    private void cmbProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductosActionPerformed
//        int indice = this.productoSeleccionado();
//        if (indice >= 0)
//        txtPrecio.setText(lP.get(indice)[2]);
    }//GEN-LAST:event_cmbProductosActionPerformed

    private void cmbMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMarcasActionPerformed
//        // TODO add your handling code here:
//        
//        listaProducto();
    }//GEN-LAST:event_cmbMarcasActionPerformed

//     public void seleccionarMarca(){
//        MarcaControlador pdc = new MarcaControlador();
//        lM = pdc.obtenerMarcas();
//
//        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>(); //modelo vacio
//        for (String[] m : lM) {
//            modelo.addElement(m[1]); //solo saca el nombre del prod3
//        }
//        cmbMarcas.setModel(modelo);
//    }
//    
//     public void listaProducto(){
//         
//         int indiceMarca = cmbMarcas.getSelectedIndex();
//     
//         ProductoControlador p=new ProductoControlador();
//         lP=p.obtenerProductos();
//         
//         DefaultComboBoxModel<String> modelo= new DefaultComboBoxModel<>();
//         if (indiceMarca >= 0 && lM != null && !lM.isEmpty()) {
//            // Obtenemos el ID de la marca de la posición [0] del arreglo
//            int idMarca = Integer.parseInt(lM.get(Marca)[0]);
//            
//          controlador.ProductoControlador pdc=new controlador.ProductoControlador();
//          lP=pdc.obtenerProductos(idMarca);
//         }
//    
//    int indiceMarca = cmbMarcas.getSelectedIndex();
//
//        if (indiceMarca >= 0 && lM != null && !lM.isEmpty()) {
//            // Obtenemos el ID de la marca de la posición [0] del arreglo
//            int idMarca = Integer.parseInt(lM.get(indiceMarca)[0]);
//
//            ProductoControlador pdc = new ProductoControlador();
//            lP = pdc.obtenerProductos(idMarca); // Asegúrate que acepte int idMarca
//
//            DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
//            for (String[] p : lP) {
//                modelo.addElement(p[1]); // Posición 1: Nombre del Producto
//            }
//            cmbProductos.setModel(modelo);
//        }
//    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMarca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnPDF;
    private javax.swing.JComboBox<String> cmbMarcas;
    private javax.swing.JComboBox<String> cmbProductos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtADetalle;
    // End of variables declaration//GEN-END:variables
}
