/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

//import com.mysql.cj.jdbc.CallableStatement;
import controlador.ClienteControlador;
import controlador.ConexionBDD;
import controlador.DetalleFacturaControlador;
import controlador.FacturaControlador;
import controlador.MarcasControlador;
import controlador.ProductoControlador;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.ClienteRegular;
import modelo.ClienteVIP;
import modelo.DetalleFactura;
import modelo.Factura;
import modelo.Marcas;
import modelo.Producto;

/**
 *
 * @author hp
 */
public class FacturaVista2Marca extends javax.swing.JFrame {

    double total = 0;
    ArrayList<String[]> listaProducto;
    ArrayList<DetalleFactura> LDF = new ArrayList<>();
    ArrayList<String[]> listaClien = new ArrayList<>();
    ArrayList<String[]> listaMarcas;
    Cliente c;
    Factura f = new Factura();
    ArrayList<String[]> lista;
    Producto pr;

    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form FacturaVista
     */
    public FacturaVista2Marca() {
        initComponents();
        f.setListaArticulos(LDF);
        cargarProducto();
        cargarClientes();
        generarfecha();
        cargarMarca();

        //jtable
        modelo.addColumn("Producto");
        modelo.addColumn("Precio U");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Subtotal");

        jtblDetalle.setModel(modelo);

        //spinner
        SpinnerNumberModel nm = new SpinnerNumberModel(0, 0, 200, 1);
        jSpinner.setModel(nm);

        JFormattedTextField txt = ((JSpinner.DefaultEditor) jSpinner.getEditor()).getTextField();
        txt.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        cmbClientes = new javax.swing.JComboBox<>();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        cmbProductos = new javax.swing.JComboBox<>();
        lblDetalle = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();
        lblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        cmbMarca = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtTotalNet = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDescuentoCli = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnCrearFac = new javax.swing.JButton();
        rbntRegular = new javax.swing.JRadioButton();
        rbtnVIP = new javax.swing.JRadioButton();
        pgbrCarga = new javax.swing.JProgressBar();
        chbxPagaIVA = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblDetalle = new javax.swing.JTable();
        jSpinner = new javax.swing.JSpinner();
        txtStock = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblTitulo.setText("GESTIÓN DE FACTURAS");

        lblNombres.setText("Nombres:");

        cmbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClientesActionPerformed(evt);
            }
        });

        lblFecha.setText("Fecha:");

        txtFecha.setEditable(false);
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        cmbProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbProductosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmbProductosMousePressed(evt);
            }
        });
        cmbProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductosActionPerformed(evt);
            }
        });

        lblDetalle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDetalle.setText("DETALLE DE LOS PRODUCTOS");

        lblProducto.setText("PRODUCTO");

        lblCantidad.setText("CANTIDAD");

        lblSubTotal.setText("SUBTOTAL");

        txtSubTotal.setEditable(false);
        txtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubTotalActionPerformed(evt);
            }
        });
        txtSubTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSubTotalKeyReleased(evt);
            }
        });

        lblPrecio.setText("PRECIO");

        txtPrecio.setEditable(false);
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAgregar.setText("+");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnPDF.setText("GENERAR PDF");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        lblCedula.setText("Cedula");

        txtCedula.setEditable(false);
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        lblDireccion.setText("Direccion");

        txtDireccion.setEditable(false);
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        lblTelefono.setText("Telefono");

        txtTelefono.setEditable(false);
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        lblCorreo.setText("Correo");

        txtCorreo.setEditable(false);
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        lblMarca.setText("Marca");

        cmbMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMarcaActionPerformed(evt);
            }
        });

        jLabel1.setText("Total Neto ");

        txtTotalNet.setEditable(false);

        jLabel2.setText("Descuento");

        txtDescuentoCli.setEditable(false);
        txtDescuentoCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoCliActionPerformed(evt);
            }
        });

        jLabel3.setText("Total");

        txtTotal.setEditable(false);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        btnCrearFac.setText("Crear Factura");
        btnCrearFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearFacActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbntRegular);
        rbntRegular.setText("Regular");
        rbntRegular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbntRegularActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnVIP);
        rbtnVIP.setText("VIP");
        rbtnVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnVIPActionPerformed(evt);
            }
        });

        pgbrCarga.setStringPainted(true);

        chbxPagaIVA.setText("¿Paga IVA?");
        chbxPagaIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbxPagaIVAActionPerformed(evt);
            }
        });

        jtblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtblDetalle);

        jLabel4.setText("STOCK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblFecha)
                                                    .addComponent(lblNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(lblCedula)
                                                    .addGap(49, 49, 49)))
                                            .addGap(9, 9, 9)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(37, 37, 37)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblDireccion)
                                                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblTelefono)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cmbClientes, javax.swing.GroupLayout.Alignment.LEADING, 0, 246, Short.MAX_VALUE)))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rbntRegular)
                                                .addComponent(rbtnVIP)
                                                .addComponent(lblCorreo)
                                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(chbxPagaIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnAgregar)))
                                        .addComponent(lblDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cmbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40)
                                                .addComponent(cmbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblPrecio)
                                                .addGap(222, 222, 222)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(57, 57, 57)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblMarca)
                                            .addGap(194, 194, 194)
                                            .addComponent(lblProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(128, 128, 128)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(194, 194, 194)
                            .addComponent(lblTitulo))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCantidad)
                                .addComponent(jSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(439, 439, 439)
                            .addComponent(pgbrCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnPDF)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnCrearFac)
                            .addGap(115, 115, 115)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(txtTotalNet, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(54, 54, 54)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtDescuentoCli, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombres)
                            .addComponent(cmbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFecha)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCedula)
                            .addComponent(lblDireccion)
                            .addComponent(lblTelefono)
                            .addComponent(lblCorreo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtnVIP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbntRegular)
                        .addGap(18, 18, 18)
                        .addComponent(chbxPagaIVA)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDetalle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMarca)
                        .addComponent(lblProducto))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecio)
                            .addComponent(lblCantidad)
                            .addComponent(lblSubTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAgregar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalNet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescuentoCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearFac))
                .addComponent(btnPDF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pgbrCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClientesActionPerformed
        this.clienteSelecionado();
    }//GEN-LAST:event_cmbClientesActionPerformed

    private void cmbProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductosActionPerformed
        int indice = this.RPS();
        if (indice >= 0) {
            txtPrecio.setText(listaProducto.get(indice)[2]);
            txtStock.setText(listaProducto.get(indice)[4]);
       }
        //this.cantidadSpinner();

//        Producto productoSeleccionado = (Producto) cmbProductos.getSelectedItem();
//        if (productoSeleccionado != null) {
//            txtPrecio.setText(String.valueOf(productoSeleccionado.getPrecio()));
//        }
    }//GEN-LAST:event_cmbProductosActionPerformed


    private void txtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubTotalActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtSubTotalActionPerformed

    private void cmbProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbProductosMouseClicked

    }//GEN-LAST:event_cmbProductosMouseClicked

    private void cmbProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbProductosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProductosMousePressed

    private void txtSubTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSubTotalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubTotalKeyReleased


    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:

        int cantidad = (int) jSpinner.getValue();

        // Captura de la cantidad del jSpinner
        int stockActual = Integer.parseInt(listaProducto.get(this.RPS())[4]);

        if (stockActual < 5) {
            javax.swing.JOptionPane.showMessageDialog(this, "Generar el restock", "Advetencia de Stock", javax.swing.JOptionPane.WARNING_MESSAGE);
        }

        if (cantidad > stockActual) {
            javax.swing.JOptionPane.showMessageDialog(this, "La cantida ingresadaa(" + cantidad + ") supera el stock disponible (" + stockActual + ").", "Error de Stock", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        double precio = Double.parseDouble(listaProducto.get(this.RPS())[2]);
        double subtotal = precio * cantidad;

        Producto p = new Producto();
        p.setId(Integer.parseInt(listaProducto.get(this.RPS())[0]));
        p.setNombre(listaProducto.get(this.RPS())[1]);
        p.setPrecio(Double.parseDouble(listaProducto.get(this.RPS())[2]));

        //objeto detalle factura 
        DetalleFactura df = new DetalleFactura();
        df.setProducto(p);
        //df.setCantidad(cantidad);       //df.setCantidad(Integer.parseInt(txtCantidad.getText()));
        df.setSubtotal(subtotal);       //df.setSubtotal(Double.parseDouble(txtSubTotal.getText())); 
        df.setCantidad((int) jSpinner.getValue());

        total += df.getSubtotal();              //calculamos
        txtTotalNet.setText(total + "");       //el total sumando los subtotales

        LDF.add(df);         //Añado a la lista dinámica

        //jTable con detalle de la factura 
        String nombre = listaProducto.get(this.RPS())[1];
        //double precio = Double.parseDouble(listaProducto.get(this.RPS())[2]);
        //String cantidad = txtCantidad.getText();
        //double subtotal = Double.parseDouble(txtSubTotal.getText());

        modelo.addRow(new Object[]{
            nombre,
            precio,
            cantidad,
            subtotal,});

        //PROGRESS BAR en detalle 
        pgbrCarga.setValue(50);
        Thread t1 = new Thread() {
            @Override
            public void run() {
                //txtADetalle.append(df.toString());      //muestro en la vista en el TextArea
                while (pgbrCarga.getValue() <= 100) {
                    pgbrCarga.setValue(pgbrCarga.getValue() + 10);
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {
                        System.getLogger(FacturaVista2Marca.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                    }
                }
            }
        };
        t1.start();

        this.limpiarDetalle();
        System.out.println("------++++++++++----------" + c.getId()); 

        f.setListaArticulos(LDF);
        f.setCliente(c);
        
//        subtotal += (int)jSpinner.getValue() * precio;              
//        txtSubTotal.setText(subtotal + "");
//        
//        txtTotal.setText(f.calcularTotalNeto()+"");
        this.calcularTotales();
    }//GEN-LAST:event_btnAgregarActionPerformed

    public void calcularTotales() {
    double descuento = 0.0;

    boolean esRegular = rbntRegular.isSelected() || (c != null && c instanceof ClienteRegular);
    
    if (esRegular && total > 1000) {
        descuento = total * 0.05;
    }
    double baseImponible = total - descuento;
    double iva = 0.0;
    if (chbxPagaIVA.isSelected()) {
        iva = baseImponible * 0.15; 
    }
    double totalAPagar = baseImponible + iva;

    txtTotalNet.setText(String.format("%.2f", total));
    txtDescuentoCli.setText(String.format("%.2f", descuento));
    txtTotal.setText(String.format("%.2f", totalAPagar));
}
    
    
//    public void cantidadSpinner(){
//        int indice = this.RPS();
//        if (indice < 0) {
//            txtSubTotal.setText("");
//            return;
//        }
//
//        try {
//            double precio = Double.parseDouble(listaProducto.get(indice)[2]);
//            int cantidad = (Integer) jSpinner.getValue();
//            txtSubTotal.setText(String.format("%.2f", precio * cantidad));
//        } catch (NumberFormatException ex) {
//            txtSubTotal.setText("");
//        }
//    }
    public void crearFactura(Cliente c) {

        f.setCliente(c);
        f.setFecha(this.generarfecha());        //f.setFecha(LocalDate.now());
        f.setListaArticulos(LDF);

        FacturaControlador fc = new FacturaControlador();
        int id = fc.insertarFacturaSP(f, total);

        DetalleFacturaControlador dfC = new DetalleFacturaControlador();
        for (DetalleFactura dt : LDF) {
            dfC.insertarDetalleFactura(dt, id);
        }

    }

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPDFActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here: 

    }//GEN-LAST:event_txtFechaActionPerformed

    private void cmbMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMarcaActionPerformed
        // TODO add your handling code here:
        cargarProducto();
    }//GEN-LAST:event_cmbMarcaActionPerformed

    private void txtDescuentoCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuentoCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoCliActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnCrearFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearFacActionPerformed
        // TODO add your handling code here:
        this.crearFactura(c);
    }//GEN-LAST:event_btnCrearFacActionPerformed

    private void rbtnVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnVIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnVIPActionPerformed

    private void rbntRegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbntRegularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbntRegularActionPerformed

    private void chbxPagaIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbxPagaIVAActionPerformed
       double iva = f.calcularIva(chbxPagaIVA.isSelected());
       double total = f.calcularTotalNeto() + iva;
       txtTotal.setText(total+"");
    }//GEN-LAST:event_chbxPagaIVAActionPerformed

    private void cargarMarca() {
        MarcasControlador mc = new MarcasControlador();
        listaMarcas = mc.obtenerMarcas();
        cmbMarca.removeAllItems();
        for (String[] marcas : listaMarcas) {
            cmbMarca.addItem(marcas[1]);
        }
    }

    private void cargarProducto() {
        int indMarca = cmbMarca.getSelectedIndex();
        int cantidad = (int) jSpinner.getValue();

        if (indMarca >= 0 && listaMarcas != null) {
            int idMarca = Integer.parseInt(listaMarcas.get(indMarca)[0]);

            ProductoControlador pc = new ProductoControlador();
            listaProducto = pc.obtenerProductosMarca(idMarca);

            cmbProductos.removeAllItems();

            if (listaProducto != null) {
                for (String[] prod : listaProducto) {
                    cmbProductos.addItem(prod[1]);
                    
                }
               
            }
        }
    }

    // cargar clientes 
    public void cargarClientes() {
        ClienteControlador cct = new ClienteControlador();
        listaClien = cct.obtenerCliente();

        cmbClientes.removeAllItems();
        for (String[] p : listaClien) {

            cmbClientes.addItem(p[1]);      //cmbClientes.addItem(p[1] + " - Cliente " + p[4]);
        }
    }

    public void crearObjetoCliente(String tipo) {
        int pos = this.RCS();
        if (tipo != null && tipo.equalsIgnoreCase("VIP")) {
            double descuentoVip = Double.parseDouble(listaClien.get(pos)[5]);
            ClienteVIP vip = new ClienteVIP();
            vip.setPorcentajeFidelidad(descuentoVip);
            c = new ClienteVIP();
        } else {
            c = new ClienteRegular();
        }
        c.setId(Integer.parseInt(listaClien.get(pos)[0]));
        c.setNombre(listaClien.get(pos)[1]);
        c.setCedula(listaClien.get(pos)[6]);
        c.setDireccion(listaClien.get(pos)[7]);
        c.setEmail(listaClien.get(pos)[2]);
        c.setTelefono(listaClien.get(pos)[3]);
    }

    public int RPS() {  //recuperar producto seleccionado 
        if (listaProducto != null && !listaProducto.isEmpty()) {
            return cmbProductos.getSelectedIndex();
        }
        return -1;
    }

    public void limpiarDetalle() {
        txtPrecio.setText("");

        txtSubTotal.setText("");

    }

    public int RCS() {    //recuperar cliente seleccionado 
        if (listaClien != null && !listaClien.isEmpty()) {
            return cmbClientes.getSelectedIndex();
        }
        return -1;
    }

    public int RPMS() {    //recuperar producto, marca seleccionado 
        if (listaMarcas != null && !listaMarcas.isEmpty()) {
            return cmbMarca.getSelectedIndex();
        }
        return -1;
    }

    public LocalDate generarfecha() {

        LocalDate fecha = LocalDate.now();
        LocalTime hora = LocalTime.now().truncatedTo(ChronoUnit.SECONDS);
        String fechaHora = fecha.toString() + "  |  " + hora.toString();
        txtFecha.setText(fechaHora);
        return fecha;
    }

    public void clienteSelecionado() {
        int indice = this.RCS();

        if (indice > -1) {

            //PROGRESS BAR en cliente  
            pgbrCarga.setValue(0);
            Thread t1 = new Thread() {
                @Override
                public void run() {

                    txtCedula.setText(listaClien.get(indice)[6]);
                    txtDireccion.setText(listaClien.get(indice)[7]);
                    txtTelefono.setText(listaClien.get(indice)[3]);
                    txtCorreo.setText(listaClien.get(indice)[2]);
                    txtDescuentoCli.setText(listaClien.get(indice)[5]);

                    while (pgbrCarga.getValue() <= 40) {
                        pgbrCarga.setValue(pgbrCarga.getValue() + 10);
                        try {
                            Thread.sleep(500);
                        } catch (InterruptedException ex) {
                            System.getLogger(FacturaVista2Marca.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                        }
                    }
                }
            };
            t1.start();

            String tipo = listaClien.get(indice)[4];
            f.setCliente(c);

            //RADIO BUTTON para el tipo de cliente 
            if (tipo.equalsIgnoreCase("VIP")) {
                rbtnVIP.setSelected(true);
                rbtnVIP.setEnabled(false);  //no se pueda marcar esa opcion 

            } else {
                rbntRegular.setSelected(true);
                rbntRegular.setEnabled(false);  //no se pueda marcar esa opcion
            }
            this.crearObjetoCliente(tipo);
        }
    }

//    public void CalcularIVA() {
//        // checkbox 
//        double subtotal = Double.parseDouble(txtTotalNet.getText());
//        double total = 0.0;
//        boolean checkbox = chbxPagaIVA.isSelected();
//
//        if (checkbox) {
//            total = subtotal + f.PagarIva();
//        } else {
//            total = subtotal;
//        }
//        txtTotal.setText(total + " ");
//    }

    public void LDF() {
        f = new Factura();
        f.calcularTotalNeto();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturaVista2Marca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturaVista2Marca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturaVista2Marca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturaVista2Marca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacturaVista2Marca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCrearFac;
    private javax.swing.JButton btnPDF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chbxPagaIVA;
    private javax.swing.JComboBox<String> cmbClientes;
    private javax.swing.JComboBox<String> cmbMarca;
    private javax.swing.JComboBox<String> cmbProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner;
    private javax.swing.JTable jtblDetalle;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDetalle;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JProgressBar pgbrCarga;
    private javax.swing.JRadioButton rbntRegular;
    private javax.swing.JRadioButton rbtnVIP;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDescuentoCli;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalNet;
    // End of variables declaration//GEN-END:variables
}
