/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.MarcaControlador;
import controlador.ProductoControlador;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author sebaa
 */
public class ProductosVista extends javax.swing.JFrame {

    ArrayList<String[]> lM;
    ArrayList<String[]> lP;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProductosVista.class.getName());

    /**
     * Creates new form ProductosVista
     */
    public ProductosVista() {
        initComponents();
        seleccionarMarca();
//        seleccionarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbMarcas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        cmbProductos = new javax.swing.JComboBox<>();
        lblDetalle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbMarcas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMarcas.addActionListener(this::cmbMarcasActionPerformed);

        jLabel2.setText("MARCA");

        lblProducto.setText("PRODUCTO");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblTitulo.setText("GESTIÓN DE FACTURAS");

        cmbProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbProductosMouseClicked(evt);
            }
        });
        cmbProductos.addActionListener(this::cmbProductosActionPerformed);

        lblDetalle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDetalle.setText("DETALLE DE LOS PRODUCTOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitulo))
                        .addGap(241, 241, 241))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel2)
                                .addGap(165, 165, 165)
                                .addComponent(lblProducto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(166, 166, 166))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(26, 26, 26)
                .addComponent(lblDetalle)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMarcasActionPerformed
        // TODO add your handling code here:
        int indice = cmbMarcas.getSelectedIndex();
        if (lM != null && !lM.isEmpty() && indice >= 0) {
            int idMarca = Integer.parseInt(lM.get(indice)[0]);
            seleccionarProductos(idMarca);
        }
    }//GEN-LAST:event_cmbMarcasActionPerformed

    private void cmbProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbProductosMouseClicked
        // TODO add your handling code here:
        //        if(lp != null || ! lp.isEmpty()){
        //            int indice = cmbProductos.getSelectedIndex(); // index devuele la posicion y el item el nombre
        //            if(indice >= 0) {
        //                txtPrecio.setText(lp.get(indice)[2]);
        //            }
        //        }
    }//GEN-LAST:event_cmbProductosMouseClicked

    private void cmbProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProductosActionPerformed

    public void seleccionarMarca() {
        MarcaControlador marca = new MarcaControlador();
        lM = marca.obtenerMarcas();

        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>(); //modelo vacio
        for (String[] m : lM) {
            modelo.addElement(m[1]); //solo saca el nombre de la marca
        }
        cmbMarcas.setModel(modelo);
    }

    public void seleccionarProductos(int idMarca) {
        ProductoControlador pdc = new ProductoControlador();
        lP = pdc.obtenerProductosPorMarca(idMarca);

        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>(); //modelo vacio
        for (String[] m : lP) {
            modelo.addElement(m[1]); //solo saca el nombre de la marca
        }
        cmbProductos.setModel(modelo);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProductosVista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbMarcas;
    private javax.swing.JComboBox<String> cmbProductos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblDetalle;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
